import {
  ApiExtraModels,
  ApiProperty,
  ApiPropertyOptional,
} from '@nestjs/swagger';
import { EventGuestProfile } from './event-guest.doc';
import { PaymentProvider } from '../../../enums/payment-provider.enum';

class TwispayPaymentFormData {
  @ApiProperty()
  base64JsonRequest!: string;

  @ApiProperty()
  base64Checksum!: string;
}

class TwispayDigitalWalletPaymentData {
  @ApiProperty({
    description: 'Twispay order identifier returned by the processor',
  })
  orderId!: number;

  @ApiProperty({
    description: 'External order identifier generated by XOXNO',
  })
  externalOrderId!: string;

  @ApiProperty({
    description: 'Twispay transaction identifier bound to the wallet charge',
  })
  transactionId!: number;

  @ApiProperty({
    description: 'Flag indicating whether 3DS verification is required',
  })
  is3d!: boolean;

  @ApiProperty({
    description: 'Flag indicating whether the client must follow a redirect',
  })
  isRedirect!: boolean;

  @ApiPropertyOptional({
    description:
      'Redirect URL supplied by the processor (present when isRedirect is true)',
  })
  redirectUrl?: string;

  @ApiPropertyOptional({
    description:
      'HTTP method to use when following the redirect instructions (defaults to POST)',
  })
  redirectMethod?: string;

  @ApiPropertyOptional({
    description:
      'Key/value parameters that must accompany the redirect request, if any',
  })
  redirectParams?: Record<string, string>;
}

class StripePaymentFormData {
  @ApiProperty()
  sessionId!: string;

  @ApiProperty()
  publicKey!: string;
}

export class XMoneyRedirectParams {
  @ApiProperty({ description: 'URL to redirect to for 3D Secure' })
  url!: string;

  @ApiProperty({
    description: 'Parameters to send with the redirect',
    type: 'object',
    additionalProperties: true,
  })
  params!: Record<string, string>;

  @ApiPropertyOptional({
    description: 'HTTP method for the redirect (POST or GET)',
  })
  formMethod?: string;
}

export class XMoneyPaymentFormData {
  @ApiProperty({ description: 'Order ID from xMoney' })
  orderId!: number;

  @ApiProperty({ description: 'Transaction ID from xMoney' })
  transactionId!: number;

  @ApiPropertyOptional({ description: 'Card ID if the card was saved' })
  cardId?: number;

  @ApiPropertyOptional({
    description: 'Whether 3D Secure is required (0 or 1)',
  })
  is3d?: 0 | 1;

  @ApiPropertyOptional({ description: 'Whether a redirect is required' })
  isRedirect?: boolean;

  @ApiPropertyOptional({
    description: 'Redirect data for 3D Secure',
    type: () => XMoneyRedirectParams,
  })
  redirect?: XMoneyRedirectParams;
}

@ApiExtraModels(
  TwispayPaymentFormData,
  StripePaymentFormData,
  TwispayDigitalWalletPaymentData,
  XMoneyPaymentFormData,
)
class FiatPaymentForm {
  @ApiProperty({
    enum: PaymentProvider,
    enumName: 'PaymentProvider',
  })
  type!: PaymentProvider;

  @ApiProperty({
    oneOf: [
      { $ref: '#/components/schemas/TwispayPaymentFormData' },
      { $ref: '#/components/schemas/StripePaymentFormData' },
      { $ref: '#/components/schemas/TwispayDigitalWalletPaymentData' },
      { $ref: '#/components/schemas/XMoneyPaymentFormData' },
    ],
  })
  data!:
    | TwispayPaymentFormData
    | StripePaymentFormData
    | TwispayDigitalWalletPaymentData
    | XMoneyPaymentFormData;
}

class CryptoPaymentResult {
  @ApiProperty()
  signature!: string;

  @ApiProperty()
  data!: string;
}

export class EventRegistrationResponseDto {
  @ApiProperty({ type: () => EventGuestProfile })
  guestDoc!: EventGuestProfile;

  @ApiPropertyOptional({ type: () => FiatPaymentForm })
  fiatPaymentForm?: FiatPaymentForm;

  @ApiPropertyOptional({ type: () => CryptoPaymentResult })
  cryptoPayment?: CryptoPaymentResult;
}
