import {
  ApiExtraModels,
  ApiProperty,
  ApiPropertyOptional,
} from '@nestjs/swagger';
import { EventGuestProfile } from './event-guest.doc';
import { PaymentProvider } from '../../../enums/payment-provider.enum';

class TwispayPaymentFormData {
  @ApiProperty()
  base64JsonRequest!: string;

  @ApiProperty()
  base64Checksum!: PromiseLike<ArrayBuffer>;
}

class TwispayDigitalWalletPaymentData {
  @ApiProperty({
    description: 'Twispay order identifier returned by the processor',
  })
  orderId!: number;

  @ApiProperty({
    description: 'External order identifier generated by XOXNO',
  })
  externalOrderId!: string;

  @ApiProperty({
    description: 'Twispay transaction identifier bound to the wallet charge',
  })
  transactionId!: number;

  @ApiProperty({
    description: 'Flag indicating whether 3DS verification is required',
  })
  is3d!: boolean;

  @ApiProperty({
    description: 'Flag indicating whether the client must follow a redirect',
  })
  isRedirect!: boolean;

  @ApiPropertyOptional({
    description:
      'Redirect URL supplied by the processor (present when isRedirect is true)',
  })
  redirectUrl?: string;

  @ApiPropertyOptional({
    description:
      'HTTP method to use when following the redirect instructions (defaults to POST)',
  })
  redirectMethod?: string;

  @ApiPropertyOptional({
    description:
      'Key/value parameters that must accompany the redirect request, if any',
  })
  redirectParams?: Record<string, string>;
}

class StripePaymentFormData {
  @ApiProperty()
  sessionId!: string;

  @ApiProperty()
  publicKey!: string;
}

@ApiExtraModels(
  TwispayPaymentFormData,
  StripePaymentFormData,
  TwispayDigitalWalletPaymentData,
)
class FiatPaymentForm {
  @ApiProperty({
    enum: PaymentProvider,
    enumName: 'PaymentProvider',
  })
  type!: PaymentProvider;

  @ApiProperty({
    oneOf: [
      { $ref: '#/components/schemas/TwispayPaymentFormData' },
      { $ref: '#/components/schemas/StripePaymentFormData' },
      { $ref: '#/components/schemas/TwispayDigitalWalletPaymentData' },
    ],
  })
  data!:
    | TwispayPaymentFormData
    | StripePaymentFormData
    | TwispayDigitalWalletPaymentData;
}

class CryptoPaymentResult {
  @ApiProperty()
  signature!: string;

  @ApiProperty()
  data!: string;
}

export class EventRegistrationResponseDto {
  @ApiProperty({ type: () => EventGuestProfile })
  guestDoc!: EventGuestProfile;

  @ApiPropertyOptional({ type: () => FiatPaymentForm })
  fiatPaymentForm?: FiatPaymentForm;

  @ApiPropertyOptional({ type: () => CryptoPaymentResult })
  cryptoPayment?: CryptoPaymentResult;
}
