import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { SmartContractResult } from './smart-contract-result';
import { Transaction } from './transaction';
import { TransactionLog } from './transaction-log';
import { TransactionOperation } from './transaction-operation';

export class TransactionDetailed extends Transaction {
  @ApiProperty({
    description:
      'Array of smart contract results generated by this transaction',
    type: [SmartContractResult],
    isArray: true,
  })
  results: SmartContractResult[] = [];

  // receipt: TransactionReceipt | undefined = undefined;

  @ApiPropertyOptional({
    description: 'The price of the transaction in USD or other currency',
    example: 0.0025,
    type: Number,
  })
  price: number | undefined = undefined;

  @ApiPropertyOptional({
    description: 'The transaction log containing emitted events',
    type: TransactionLog,
  })
  logs: TransactionLog | undefined = undefined;

  @ApiProperty({
    description: 'Array of decoded operations performed in this transaction',
    type: [TransactionOperation],
    isArray: true,
  })
  operations: TransactionOperation[] = [];
}
