export enum BinanceTerminalType {
  APP = 'APP',
  WEB = 'WEB',
  WAP = 'WAP',
  MINI_PROGRAM = 'MINI_PROGRAM',
  OTHERS = 'OTHERS',
}

export enum BinanceGoodsType {
  TANGIBLE = '01',
  VIRTUAL = '02',
}

export enum BinanceBizType {
  PAY = 'PAY',
  REFUND = 'REFUND',
  PAYOUT = 'PAYOUT',
  PAY_REFUND = 'PAY_REFUND',
  BALANCE = 'BALANCE',
}

export enum BinanceBizStatus {
  PAY_SUCCESS = 'PAY_SUCCESS',
  PAY_CLOSED = 'PAY_CLOSED',
}

export enum BinanceGoodsCategory {
  ELECTRONICS_COMPUTERS = '0000',
  BOOKS_MUSIC_MOVIES = '1000',
  HOME_GARDEN_TOOLS = '2000',
  CLOTHES_SHOES_BAGS = '3000',
  TOYS_KIDS_BABY = '4000',
  AUTOMOTIVE_ACCESSORIES = '5000',
  GAME_RECHARGE = '6000',
  ENTERTAINAMENT_COLLECTION = '7000',
  JEWELRY = '8000',
  DOMESTIC_SERVICE = '9000',
  BEAUTY_CARE = 'A000',
  PHARMACY = 'B000',
  SPORTS_OUTDOORS = 'C000',
  FOOD_GROCERY_HEALTH_PRODUCTS = 'D000',
  PET_SUPPLIES = 'E000',
  INDUSTRY_SCIENCE = 'F000',
  OTHERS = 'Z000',
}
