export enum TransactionOperationAction {
  none = 'none',
  transfer = 'transfer',
  burn = 'burn',
  addQuantity = 'addQuantity',
  create = 'create',
  multiTransfer = 'multiTransfer',
  localMint = 'localMint',
  localBurn = 'localBurn',
  wipe = 'wipe',
  freeze = 'freeze',
  writeLog = 'writeLog',
  signalError = 'signalError',
  buy = 'buy',
  buySft = 'buySft',
  bulkBuy = 'bulkBuy',
  acceptOffer = 'acceptOffer',
  endAuction = 'endAuction',
  listing = 'listing',
  withdraw = 'withdraw',
  changePrice = 'changePrice',
  bid = 'bid',
  sendOffer = 'sendOffer',
  withdrawOffer = 'withdrawOffer',
}
