export enum WalletClientType {
  XOXNO = 'xoxno',
  WEBWALLET = 'webwallet',
  MAIAR_V2 = 'maiar_v2',
  SUI = 'sui',
  LEDGER = 'ledger',
  EXTENSION = 'extension',
  NATIVE = 'native',
  ZK_LOGIN = 'zkLogin',
  METAMASK = 'metamask',
  EVM = 'evm',
  SOLANA = 'solana',
  PASSKEY = 'passkey',
  FREIGHTER = 'freighter',
  XBULL = 'xbull',
  HANA = 'hana',
  LOBSTR = 'lobstr',
  STELLAR_WALLET_CONNECT = 'wallet_connect',
  ALBEDO = 'albedo',
  HOT_WALLET = 'hot_wallet',
  RABET = 'rabet',
  KLEVER = 'klever',
}
