export enum MarketplaceActivity {
  LISTING_CREATE = 'listingCreate',
  LISTING_WITHDRAW = 'listingWithdraw',
  LISTING_UPDATE = 'listingUpdate',
  AUCTION_BID = 'auctionBid',
  AUCTION_OUT_BID = 'auctionOutBid',
  OFFER_CREATE = 'offerCreate',
  OFFER_WITHDRAW = 'offerWithdraw',
  OFFER_REJECT = 'offerReject',
  GLOBAL_OFFER_CREATE = 'globalOfferCreate',
  GLOBAL_OFFER_WITHDRAW = 'globalOfferWithdraw',
  TRADE = 'trade',
  BULK_TRADE = 'bulkTrade',
  AUCTION_TRADE = 'auctionTrade',
  OTHER_TRADE = 'otherTrade', // fiat or binance buy
  OFFER_TRADE = 'offerTrade',
  GLOBAL_OFFER_TRADE = 'globalOfferTrade',
  DEPOSIT = 'deposit',
  WITHDRAW_DEPOSIT = 'withdrawDeposit',
}
